apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: go-simple-webserver
  labels:
    app: go-simple-webserver
spec:
  replicas: 10
  strategy:
    canary:
      steps:
        - setWeight: 25       # Shift 25% of traffic to the canary
        - pause: { duration: 120s }  # Pause for 120 seconds
        - setWeight: 75       # Shift 75% of traffic to the canary
        - pause: { duration: 120s }  # Pause for another 120 seconds
        - setWeight: 100      # Shift 100% of traffic to the canary
  selector:
    matchLabels:
      app: go-simple-webserver
  template:
    metadata:
      labels:
        app: go-simple-webserver
    spec:
      containers:
        - name: webserver
          image: ghcr.io/andreigm18/no:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
